language: go
sudo: false
go:
  - tip
os:
  - linux
install:
  - go get github.com/smartystreets/goconvey
script:
  - go build -v
  - ./.test.sh
after_success:
  - bash <(curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/ReanGD/go-morphy")
notifications:
  email:
    recipients:
      - reangd@yandex.ru
    on_success: never
    on_failure: always
